export const PERMISSIONS = {
  // User Management
  USER: {
    VIEW: 'VIEW_USER',
    ADD: 'ADD_USER',
    UPDATE: 'UPDATE_USER',
    DELETE: 'DELETE_USER',
    MANAGE_PERMISSION: 'MANAGE_USER_PERMISSION',
    CHANGE_POSITION: 'CHANGE_USER_POSITION',
  },

  // Position Management
  POSITION: {
    VIEW: 'VIEW_POSITION',
    ADD: 'ADD_POSITION',
    UPDATE: 'UPDATE_POSITION',
    DELETE: 'DELETE_POSITION',
  },

  // Permission Management
  PERMISSION: {
    VIEW: 'VIEW_PERMISSION',
    ADD: 'ADD_PERMISSION',
    UPDATE: 'UPDATE_PERMISSION',
    DELETE: 'DELETE_PERMISSION',
  },

  // Tree Management
  TREE: {
    VIEW: 'VIEW_TREE',
    ADD: 'ADD_TREE',
    UPDATE: 'UPDATE_TREE',
    DELETE: 'DELETE_TREE',
  },

  // Person Management
  PERSON: {
    VIEW: 'VIEW_PERSON',
    ADD: 'ADD_PERSON',
    UPDATE: 'UPDATE_PERSON',
    DELETE: 'DELETE_PERSON',
  },

  // Relationship Management
  RELATIONSHIP: {
    VIEW: 'VIEW_RELATIONSHIP',
    ADD: 'ADD_RELATIONSHIP',
    UPDATE: 'UPDATE_RELATIONSHIP',
    DELETE: 'DELETE_RELATIONSHIP',
  },
} as const;
